version: "3.9"

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: traffic_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userPassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  traffic_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traffic_app
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/traffic_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootPassword
    depends_on:
      mysql_db:
        condition: service_healthy

volumes:
  mysql_data:



